//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.Properties.Resources" +
                            "", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported configuration.  To enable antimalware, specify a value of true for the AntimalwareEnabled element..
        /// </summary>
        internal static string ServiceExtensionCannotFindAntimalwareEnableSetting {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindAntimalwareEnableSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find storage keys for the account name: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindStorageAccountKey {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindStorageAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find storage service for the account name: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindStorageAccountName {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindStorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageAccountName element was not found in the existing monitoring configuration..
        /// </summary>
        internal static string ServiceExtensionExistingMonitoringConfigurationIsMissingStorageAccountNameElement {
            get {
                return ResourceManager.GetString("ServiceExtensionExistingMonitoringConfigurationIsMissingStorageAccountNameElement" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account name required for antimalware monitoring was not found in in the configuration file or the parameter list. .
        /// </summary>
        internal static string ServiceExtensionMissingAntimalwareMonitoringStorageAccountName {
            get {
                return ResourceManager.GetString("ServiceExtensionMissingAntimalwareMonitoringStorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing {0}.{1} extensions enabled on given roles..
        /// </summary>
        internal static string ServiceExtensionNoExistingExtensionsEnabledOnRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionNoExistingExtensionsEnabledOnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing default {0} configuration for all roles from Cloud Service {1}..
        /// </summary>
        internal static string ServiceExtensionRemovingFromAllRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingFromAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} configuration for {1} from Cloud Service {2}..
        /// </summary>
        internal static string ServiceExtensionRemovingFromSpecificRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingFromSpecificRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default {0} configuration exists applying default configuration to {1}..
        /// </summary>
        internal static string ServiceExtensionRemovingSpecificAndApplyingDefault {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingSpecificAndApplyingDefault", resourceCulture);
            }
        }
    }
}
